/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CVDemo;

import com.stuypulse.stuylib.math.Angle;
import com.stuypulse.stuylib.math.Vector2D;

import CVDemo.commands.AlignmentCommand;
import CVDemo.commands.ControlCommand;
import CVDemo.entity.Entity;

public class App {
    
    public static void main(String[] args) {
        WorldDisplay world = new WorldDisplay();
        Robot2 robot = new Robot2(0.5);

        Entity[] targets = new Entity[] {
            new Target2(new Vector2D(7.5, 5), Angle.kZero),
            new Target2(new Vector2D(2.5, 5), Angle.fromDegrees(45)),
            new Target2(new Vector2D(5, -5), Angle.fromDegrees(-45))
        };

        Limelight limelight = new Limelight(robot, targets);

        AlignmentCommand aligner = new AlignmentCommand(robot, limelight);
        ControlCommand drive = new ControlCommand(robot, world);

        world.addEntity(limelight);
        world.addEntity(robot);
        world.addEntity(targets);

        limelight.turnOn();

        while(world.isVisible()) {

            if(world.getKey("space")) {
                limelight.turnOn();
                if (world.getKey("q") && limelight.isVisible()) 
                    aligner.execute();
                else
                    drive.execute();
            } else {
                limelight.turnOff();
                drive.execute();
            }

            world.step();
            world.draw();
            world.update();

            try {
                Thread.sleep(2);
            } catch (InterruptedException interruptedException) {
                System.out.println("Thread Sleeping was interrupted!");
                System.out.println("This literally never happens in the main function!");
                break;
            }
        }
    }
}
